"""The single source of truth for public CLI commands and their metadata."""

from __future__ import annotations

from copy import deepcopy
from typing import Any


_COMMAND_CATALOG: tuple[dict[str, Any], ...] = (
    {
        "command": "commands",
        "purpose": "Discover every supported CLI command and its agent contract.",
        "parameters": [{"name": "--json", "required": True, "type": "flag"}],
        "roles": ["all"],
        "data_scope": "none",
        "side_effect": "none",
        "risk_level": "low",
        "agent_callable": True,
        "confirmation": "none",
        "output_schema": {"data": {"commands": "Command[]"}},
        "sensitive_data": "none",
        "examples": ["dydata commands --json"],
        "errors": ["INTERNAL_ERROR"],
    },
    {
        "command": "auth.login",
        "purpose": "Sign in interactively and store credentials locally.",
        "parameters": [],
        "roles": ["all"],
        "data_scope": "none",
        "side_effect": "local_credential",
        "risk_level": "medium",
        "agent_callable": False,
        "confirmation": "interactive",
        "output_schema": {"data": {"authenticated": "boolean"}},
        "sensitive_data": "credential",
        "examples": ["dydata auth login"],
        "errors": ["AUTH_REQUIRED", "INTERNAL_ERROR"],
    },
    {
        "command": "auth.logout",
        "purpose": "Remove the locally stored CLI credential.",
        "parameters": [],
        "roles": ["all"],
        "data_scope": "none",
        "side_effect": "local_credential",
        "risk_level": "low",
        "agent_callable": False,
        "confirmation": "interactive",
        "output_schema": {"data": {"authenticated": "boolean"}},
        "sensitive_data": "credential",
        "examples": ["dydata auth logout"],
        "errors": ["INTERNAL_ERROR"],
    },
    {
        "command": "auth.status",
        "purpose": "Report whether a locally stored CLI credential is usable.",
        "parameters": [{"name": "--json", "required": True, "type": "flag"}],
        "roles": ["all"],
        "data_scope": "current_identity",
        "side_effect": "none",
        "risk_level": "low",
        "agent_callable": True,
        "confirmation": "none",
        "output_schema": {"data": {"authenticated": "boolean", "expires_at": "datetime"}},
        "sensitive_data": "credential_metadata",
        "examples": ["dydata auth status --json"],
        "errors": ["AUTH_REQUIRED", "AUTH_EXPIRED", "INTERNAL_ERROR"],
    },
    {
        "command": "stores.list",
        "purpose": "List stores available within the caller's data scope.",
        "parameters": [{"name": "--json", "required": True, "type": "flag"}],
        "roles": ["viewer", "store", "manager", "admin"],
        "data_scope": "authorized_stores",
        "side_effect": "none",
        "risk_level": "low",
        "agent_callable": True,
        "confirmation": "none",
        "output_schema": {"data": {"stores": "Store[]"}},
        "sensitive_data": "store_identity",
        "examples": ["dydata stores list --json"],
        "errors": ["AUTH_REQUIRED", "SCOPE_DENIED", "API_UNAVAILABLE"],
    },
    {
        "command": "clues.follow-up-stats",
        "purpose": "Summarize clue follow-up results for authorized stores.",
        "parameters": [
            {
                "name": "--from",
                "dest": "date_from_text",
                "normalized_dest": "date_from",
                "required": False,
                "type": "YYYY-MM-DD",
            },
            {
                "name": "--to",
                "dest": "date_to_text",
                "normalized_dest": "date_to",
                "required": False,
                "type": "YYYY-MM-DD",
            },
            {
                "name": "--store-id",
                "dest": "store_ids",
                "required": False,
                "repeatable": True,
                "type": "string",
            },
            {
                "name": "--output",
                "required": False,
                "type": "json|table",
                "choices": ["json", "table"],
                "default": "json",
            },
        ],
        "date_range": {
            "start": "--from",
            "end": "--to",
            "default_days": 7,
            "max_inclusive_days": 366,
        },
        "roles": ["viewer", "store", "manager", "admin"],
        "data_scope": "authorized_stores",
        "side_effect": "none",
        "risk_level": "low",
        "agent_callable": True,
        "confirmation": "none",
        "output_schema": {"data": {"stores": "FollowUpStats[]", "totals": "FollowUpStats"}},
        "sensitive_data": "store_metrics",
        "examples": [
            "dydata clues follow-up-stats",
            "dydata clues follow-up-stats --from 2026-07-01 --to 2026-07-07 --store-id store-a --output table",
        ],
        "errors": ["AUTH_REQUIRED", "SCOPE_DENIED", "INVALID_ARGUMENT", "API_UNAVAILABLE"],
    },
    {
        "command": "version",
        "purpose": "Report the installed CLI and schema versions.",
        "parameters": [{"name": "--json", "required": True, "type": "flag"}],
        "roles": ["all"],
        "data_scope": "none",
        "side_effect": "none",
        "risk_level": "low",
        "agent_callable": True,
        "confirmation": "none",
        "output_schema": {"data": {"cli_version": "string", "schema_version": "string"}},
        "sensitive_data": "none",
        "examples": ["dydata version --json"],
        "errors": ["INTERNAL_ERROR"],
    },
)


def command_catalog() -> list[dict[str, Any]]:
    """Return a copy so callers cannot mutate the authoritative registry."""
    return deepcopy(list(_COMMAND_CATALOG))
